### ISSUE TITLE
os: three easy pieces

### ISSUE THREAD

**Issue by remzi-arpacidusseau** [amilajack/personal-readings#5]
Hi -
Please remove the OSTEP book from your github - it
is copyrighted material, and we distribute it through
our website. This avoids certain problems for us - 
i.e., people  reading old versions, etc. 
thanks!
Remzi (author)

**Comment by amilajack** [comment]
Just deleted it from the repo

**Comment by remzi-arpacidusseau** [comment]
thanks -
and sorry for the pain.
best,
Remzi
